
@controller=administrator
@host=http://localhost:5500/api/{{controller}}
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDYsInJvbGVzIjpbImFkbWluaXN0cmF0b3IiXSwiaWF0IjoxNTc5ODcxNzIxLCJleHAiOjE1Nzk5NTgxMjF9.lMj5ieNDSkiucDEgUqtAc1Nkig4m0n9XbR5SeXQQS7Q

POST   http://localhost:5500/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username":"ocph23.test@gmail.com",
    "password": "administrator"
}

####
Get   http://localhost:5500/api/auth/profile HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

####
GET {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
####


####
GET {{host}}/1 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
####

POST {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
    "nama":"Santi",
    "email":"oncph23.test@gmail.com",
    "telepon":"0811481111",
    "iduniversitas":1 
}


####

PUT {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
    "idadministrator": 3,
    "idusers": 46,
    "iduniversitas": 1,
    "nama": "Santi Saja",
    "telepon": "0811481111",
    "namauniversitas": "USTJ"
  }


####

DELETE {{host}}/2 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}