
@controller=peraturan
@host=http://localhost:5500/api/{{controller}}
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNTc5MTgwODc4LCJleHAiOjE1NzkyNjcyNzh9.vWlOrUzpxA7eQ-GPmgkRXK-Gpxh-6-qoGfkqQtA7nnM


####
GET {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
####


####
GET {{host}}/1 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}
####

POST {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
    "tahun":"No 23 2020"
}


####

PUT {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
  "idperaturan": 1,
  "tahun": "No 23 1999"
}


####

DELETE {{host}}/2 HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}