GET http://localhost:5500/api/universitas HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsInJvbGUiOiJhZG1pbiIsImlhdCI6MTU3Njc5MjIzNCwiZXhwIjoxNTc2ODc4NjM0fQ.Nm_6Jm2Ta6vLU_fJvXXZEq_EFEb0_mAciOXOOFua_JM